### ISSUE TITLE
Down

### ISSUE THREAD

**Issue by Hak333** [v-Cx/Discord-Account-Generator#10]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.gmailnator.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000002D48EE1E588>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

**Comment by Hak333** [comment]
wrong

**Comment by v-Cx** [comment]
This error is caused by your server. Since the MySQL connection is being made, there is a connection problem in the port or host.
