### ISSUE TITLE
SQL 

### ISSUE THREAD

**Issue by Galerici** [v-Cx/Discord-Account-Generator#2]
Hocam merhaba sql server nasıl kuracağız?

**Comment by v-Cx** [comment]
Merhaba. @Galerici 
cPanel üzerinden bir mysl database açın. Ardından .env dosyasında bulunan mysql bilgilerini istenildiği şekilde doldurun. Tüm işlem bu kadar.

**Comment by v-Cx** [comment]
Problem çözüldüğü zaman "çözüldü" olarak geri dönüş yapın lütfen. Eğer sorun devam ederse size yardımcı olmaya devam edeceğim.
