### ISSUE TITLE
WTF did u do

### ISSUE THREAD

**Issue by PhilippStecher** [v-Cx/Discord-Account-Generator#5]
ALL FILES ARE MISSING. package-lock.json, cmd folder. node-modules. Like what the heck did u do lmao

**Comment by PhilippStecher** [comment]
https://github.com/PhilippStecher/Read-Decompiled-GTAV-Scripts What a normal NodeJS folder should look like :)

**Comment by v-Cx** [comment]
Thanks for your suggestion. Your problem has been resolved and you have been banned.
